apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai2es
spec:
  schedule: "*/5 * * * *"            ## Defined schedule using the *nix style cron syntax
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ai2es-watch
        spec:
          containers:
          - name: ai2es
            image: vprzybylo/ai2es_watch:v1.0.0
            volumeMounts:
            - name: nysm
              mountPath: /rdma/dgx-a100/NYSM/archive/nysm/
            - name: home
              mountPath: /home/vanessa/hulk/
            command: ["/bin/sh"]
            args: ["-c", "python /home/vanessa/hulk/ai2es/ai2es/watch.py"]
          volumes:
          - name: nysm
            hostPath:
              path: /rdma/dgx-a100/NYSM/archive/nysm/
          - name: home
            hostPath:
              path: /home/vanessa/hulk/
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure    ##  Restart Policy in case container failed
