version: "2.1"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile_codercom
    image: vprzybylo/code_server_ai2es:v0.0.0
    container_name: code-server-ai2es
    environment:
      - PORT=9443 code-server-ai2es
      - PUID=1001
      - PGID=1001
      - DEFAULT_WORKSPACE=/raid/vanessa/ai2es/
      - TZ=America/New_York
#    shm_size: '100G'
    user: ${UID_GID}
    volumes:
      - /raid/NYSM/archive/nysm/cam_photos/:/ai2es/raw_photos/
      - /home/vanessa/:/home/vanessa/
      - /raid/vanessa/ai2es/:/ai2es/
      - ${HOME}/.local/share/code-server/:/home/vanessa/.local/share/code-server
      - ${PWD}:/home/coder/project
#    deploy:
#      resources:
#        limits:
#          cpus: '20'
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              device_ids: [ '4,5' ]
    ports:
      - 9443:9443
    restart: unless-stopped

