FROM python:3.9-slim-buster

LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all

RUN apt-get -y update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -y update && apt-get install -y --no-install-recommends \
	python3-setuptools \
	python3-pip \
        && apt-get clean all && rm -rf /var/lib/apt/lists/*


RUN pip3 install --upgrade pip
COPY requirements_dev.txt requirements_dev.txt
RUN pip3 install -r requirements_dev.txt

# install cocpit package for dev
COPY setup.py setup.py
COPY README.md README.md
RUN pip3 install -e .
